replicaCount: 2

image:
  repository: 762233764391.dkr.ecr.us-east-1.amazonaws.com/prima-api
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

serviceAccount:
  name: app-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::762233764391:role/prima-tech-challenge-cluster-app-role

