apiVersion: apps/v1
kind: Deployment
metadata:
  name: prima-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: prima-api
  template:
    metadata:
      labels:
        app: prima-api
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: prima-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /users
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /users
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

